apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "auto-youtube-dl.fullname" . }}
  labels:
  {{- include "auto-youtube-dl.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
